@echo off
title [🚀] Binance Webhook Bot Başlatılıyor...
echo [🔁] Sanal ortam aktifleştiriliyor...
call venv\Scripts\activate

echo [📦] Gerekli paketler yükleniyor...
pip install -q -r requirements.txt

echo [🌐] Flask bot başlatılıyor...
python app.py

pause
